### ISSUE TITLE
WPML

### ISSUE THREAD

**Issue by ming2014** [PAYONE-GmbH/woocommerce-3#58] opened 2020-09-19 13:03 UTC
WooCommerce version: 4.2.2
WordPress version: 5.4.2
PHP version: 7.2.24
BS PAYONE Payment for WooCommerce 3 Version 1.7.1
We use plugins: WPML

Online website in 3 languages, English, Chinese, German.
In English, all payment procedures are correct, and guests will be redirected to the online website after payment.
However, in the Chinese and German interface, after the guest has successfully paid, he cannot jump to the online store.
**Erro:**
<img width="454" alt="Payone1" src="https://user-images.githubusercontent.com/6830913/93667775-accf8980-fa88-11ea-983a-ac7b58e5ff3e.png">
**after the guest has successfully paid:**
![payone2](https://user-images.githubusercontent.com/6830913/93667780-b2c56a80-fa88-11ea-8fb1-5740e7dc1048.jpg)

The guest's payment is successful, but our website cannot accept the feedback of successful payment. After 15 minutes, the website thinks that the guest's payment is unsuccessful, and then deletes the order.

thank you!

**Comment by fjbender** [comment] 2020-09-25 06:21
Hi,

could you send over one or two affected TXIDs oder your MID and transaction timestamp to integrations@payone.com?
The second screen shot suggests some problem in the 3D Secure sequence with a Danske Bank customer that I'd like to analyze further. As this is quite the new service and banks are only now adopting 3DS2, I suspect that there might be an encoding problem with Chinese characters and/or German/Danish umlauts.

**Comment by fjbender** [comment] 2020-09-25 06:26
Additionally, the success URL shown in the first screenshot looks somewhat bogus with the two ? operators. Maybe, WPML somewhat breaks URL building in our plugin.

**Comment by ming2014** [comment] 2020-09-26 21:19
hi
i will sent E-mail to: integrations@payone.com
thank you

**Comment by fjbender** [comment] 2020-09-28 07:49
Hi,

I can confirm that WPML seems to break URL generation in our plugin, which leads to the customer receiving the "ERROR" message. Additionally, we were unable to post the transaction status indicating the success of the transaction, which might also be related to WPML.

Maybe we can improve the function that generates the URLs to be more robust: https://github.com/PAYONE-GmbH/woocommerce-3/blob/265fc7fc7842da83ebf17e252186caaacc3c58c3/src/Payone/Plugin.php#L117-L124

I'll talk to dev about it.

**Comment by ming2014** [comment] 2020-09-28 20:56
Thank you for your feedback

**Comment by ming2014** [comment] 2020-10-04 13:56
Hi，
Is there any progress on this plugin? We are currently unable to use PayOne's services. If there is no progress, we must change to another service provider.

**Comment by fjbender** [comment] 2020-10-05 06:14
We're still working on this.

**Comment by hreinberger** [comment] 2020-10-05 09:21
Hi @ming2014 we introduced a quick fix in #60 and are currently testing it for regressions. Are you able to check out the code on a testing environment using WPML to see if it actually fixes the issue?

**Comment by ming2014** [comment] 2020-10-05 12:16
> 
> 
> Hi @ming2014 we introduced a quick fix in #60 and are currently testing it for regressions. Are you able to check out the code on a testing environment using WPML to see if it actually fixes the issue?

i will test, thank you!

**Comment by hreinberger** [comment] 2020-10-08 10:37
Update from our regression testing: This PR at least doesn't break anything. Did you have any chance to test this yet @ming2014 ?

**Comment by ming2014** [comment] 2020-10-08 12:02
> 
> 
> Update from our regression testing: This PR at least doesn't break anything. Did you have any chance to test this yet @ming2014 ?

Sorry, we don't know how to test, do we need to download the code here and install it in the usual way of installing plug-ins?
<img width="359" alt="payone" src="https://user-images.githubusercontent.com/6830913/95455922-d89aac80-096e-11eb-85f3-e2e524e8894b.png">

**Comment by hreinberger** [comment] 2020-10-08 13:21
Hi @ming2014 I've prepared a patched version of the plugin for you.
[woocommerce-3-master.zip](https://github.com/PAYONE-GmbH/woocommerce-3/files/5348071/woocommerce-3-master.zip)

You can extract this into the `/wp-content/plugins/payone-woocommerce-3` folder on your webserver and then use the wordpress plugin manager to install the plugin. Make sure to do this on a dedicated testing system though because this code is technically untested.

**Comment by ming2014** [comment] 2020-10-09 12:13
> 
> 
> Hi @ming2014 I've prepared a patched version of the plugin for you.
> [woocommerce-3-master.zip](https://github.com/PAYONE-GmbH/woocommerce-3/files/5348071/woocommerce-3-master.zip)
> 
> You can extract this into the `/wp-content/plugins/payone-woocommerce-3` folder on your webserver and then use the wordpress plugin manager to install the plugin. Make sure to do this on a dedicated testing system though because this code is technically untested.

We tested it and there is no problem in the English or German interface, but there are still errors in the Chinese interface.
PAYONE Vorgangsnummer: 458548099
<img width="489" alt="WeChat Screenshot_20201009095024" src="https://user-images.githubusercontent.com/6830913/95581510-7195fa00-0a39-11eb-9dd5-87376c2cff1b.png">
<img width="470" alt="WeChat Screenshot_20201009100911" src="https://user-images.githubusercontent.com/6830913/95581577-85d9f700-0a39-11eb-9acf-1d2071e19508.png">

**Comment by hreinberger** [comment] 2020-10-12 06:38
Thanks for testing this out, we'll recheck

**Comment by ming2014** [comment] 2020-10-18 22:01
hi
How long will it take to resolve this issue?
We have not used PayOne service for almost 2 months, thank you.

**Comment by hreinberger** [comment] 2020-10-21 14:42
Hi @ming2014 
we think we found the error with the chinese interface. Could you once again try out this test plugin?
[woocommerce-3-master.zip](https://github.com/PAYONE-GmbH/woocommerce-3/files/5416676/woocommerce-3-master.zip)

**Comment by ming2014** [comment] 2020-10-22 19:56
> 
> 
> Hi @ming2014
> we think we found the error with the chinese interface. Could you once again try out this test plugin?
> [woocommerce-3-master.zip](https://github.com/PAYONE-GmbH/woocommerce-3/files/5416676/woocommerce-3-master.zip)

Now it doesn't work in German and Chinese interface.
Vorgangsnummer: 462414750
Vorgangsnummer: 462415648

**Comment by hreinberger** [comment] 2020-10-23 08:34
oof. We'll have another look at it.

**Comment by hreinberger** [comment] 2020-10-27 13:40
Hi @ming2014 
you know the deal, could you try again with this plugin zip? I've applied for a dev license of WPML, but until that arrives it would be great if you could provide feedback.
[payone-woocommerce-3-plugin-PDK-50-fix-wpml-links.zip](https://github.com/PAYONE-GmbH/woocommerce-3/files/5445655/payone-woocommerce-3-plugin-PDK-50-fix-wpml-links.zip)

we've attempted the fix more broadly this time to hopefully catch all instances of this error.

**Comment by ming2014** [comment] 2020-10-27 21:45
Now on my test website, the English, Chinese, and German interfaces all return errors, and the payment on payone is all successful.

<img width="430" alt="WeChat Screenshot_20201027224250" src="https://user-images.githubusercontent.com/6830913/97365444-fc824b80-18a5-11eb-9c81-fc220eb90943.png">

**Comment by hreinberger** [comment] 2020-10-29 14:53
Hi @ming2014 we were able to get a developer license for WPML so that you don't need to be our Guinea Pig anymore. We're reproducing the issue internally and will get back to you once we're certain our fix works.

**Comment by hreinberger** [comment] 2020-11-04 07:30
Hi @ming2014 
[payone-woocommerce-3-plugin-fix-wpml-links.zip](https://github.com/PAYONE-GmbH/woocommerce-3/files/5486137/payone-woocommerce-3-plugin-fix-wpml-links.zip)
This will hopefully be the final fix. We installed WPML and tested it with English and Chinese translations. Could you verify that the issue is resolved with the attached zip?

**Comment by ming2014** [comment] 2020-11-04 23:06
Hello
There is no problem in the English interface, but the Chinese and German interfaces have the following errors:
<img width="597" alt="WeChat Screenshot_20201104235352" src="https://user-images.githubusercontent.com/6830913/98177332-b149e780-1efa-11eb-924a-1364669d49c8.png">
<img width="631" alt="WeChat Screenshot_20201105000003" src="https://user-images.githubusercontent.com/6830913/98177338-b313ab00-1efa-11eb-9f04-63d4192dec35.png">

**Comment by ming2014** [comment] 2020-11-16 21:32
Will this error be fixed?

**Comment by hreinberger** [comment] 2020-11-19 14:27
Hi @ming2014 we tried extensively to replicate this error, but this issue doesn't occur on our test systems. The plugin should now be fully compatible with WPML, so maybe there's something different wrong here. In most cases with this specific error there are customizations of the theme that prevent our JS from firing properly during checkout. Have you tried using the default storefront theme?

**Closed** 2020-11-20 13:19 UTC

**Comment by ming2014** [comment] 2020-11-24 14:37
> 
> 
> Hi @ming2014 we tried extensively to replicate this error, but this issue doesn't occur on our test systems. The plugin should now be fully compatible with WPML, so maybe there's something different wrong here. In most cases with this specific error there are customizations of the theme that prevent our JS from firing properly during checkout. Have you tried using the default storefront theme?

Hi
Close all the plug-ins, and then reactivate all the plug-ins, the problem has been solved. Thank you!
