### ISSUE TITLE
Warning DataTransfer $this->parameter_bag is null

### ISSUE THREAD

**Issue by vardumper** [PAYONE-GmbH/woocommerce-3#23] opened 2019-05-14 13:08 UTC
Stack trace
E_WARNING: array_key_exists() expects parameter 2 to be array, null given
in array_key_exists called at /bla/bla/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php (93)

**Comment by hreinberger** [comment] 2019-05-21 07:19
Hi @vardumper 
unfortunately we couldn't reproduce this behavior. Could you give us more insight into this issue? Are you using the current master? How can we reproduce this issue?

**Comment by vardumper** [comment] 2019-05-21 07:55
Hi guys. We are using the 1.4.0 version called wpackagist-plugin/bs-payone-woocommerce in our composer-based stack. (@see https://wpackagist.org/search?q=payone&type=any&search= with last commit date 2018-12-13 15:34:44).
Unfortunately I don't have that trace anymore, but I'll append the surrounding lines, hopefully that helps clarify what happened.
I did not manage to use your repo from GitHub since there's no composer.json in place. (I'll open a separate request for that).

We use Nginx and PHP7.2 fpm

```
HP message: PHP Notice:  post wurde <strong>fehlerhaft aufgerufen</strong>. Order properties should not be accessed directly. Backtrace: include('wp-admin/edit-form-advanced.php'), do_meta_boxes, WC_Meta_Box_Order_Data::output, do_action('woocommerce_admin_order_data_after_order_details'), WP_Hook->do_action, WP_Hook->apply_filters, wc_boniversum_api->show_order_meta, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Weitere Informationen: <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress (engl.)</a> (Diese Meldung wurde in Version 3.0 hinzugefügt.) in /var/www/whatever/releases/20190514121609/web/wp-includes/functions.php on line 4773
PHP message: PHP Notice:  post wurde <strong>fehlerhaft aufgerufen</strong>. Order properties should not be accessed directly. Backtrace: include('wp-admin/edit-form-advanced.php'), do_meta_boxes, WC_Meta_Box_Order_Data::output, do_action('woocommerce_admin_order_data_after_order_details'), WP_Hook->do_action, WP_Hook->apply_filters, wc_boniversum_api->show_order_meta, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Weitere Informationen: <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress (engl.)</a> (Diese Meldung wurde in Version 3.0 hinzugefügt.) in /var/www/whatever/releases/20190514121609/web/wp-includes/functions.php on line 4773" while reading response header from upstream, client: 80.151.43.80, server: whatever.com, request: "GET /wp-admin/post.php?post=2669&action=edit HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "whatever.com"
2019/05/14 12:46:59 [error] 4395#4395: *180 FastCGI sent in stderr: "PHP message: testlog" while reading response header from upstream, client: 80.151.43.80, server: whatever.com, request: "GET /wp-admin/admin.php?page=payone-settings-account HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "whatever.com"
2019/05/14 12:46:59 [error] 4395#4395: *180 FastCGI sent in stderr: "PHP message: testlog" while reading response header from upstream, client: 80.151.43.80, server: whatever.com, request: "POST /wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "whatever.com"
2019/05/14 12:47:01 [error] 4395#4395: *180 FastCGI sent in stderr: "PHP message: testlog
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releas
2019/05/14 12:47:01 [error] 4395#4395: *180 FastCGI sent in stderr: "/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/whatever/releases/20190514121609/web/wp-content/plugins/bs-payone-woocommerce/src/Payone/Payone/Api/DataTransfer.php on line 93
PHP message: PHP Warning:  array_key_exists() expects parameter 2
2019/05/14 12:47:01 [error] 4395#4395: *180 upstream sent too big header while reading response header from upstream, client: 80.151.43.80, server: whatever.com, request: "GET /wp-admin/admin.php?page=payone-transaction-log HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "whatever.com"
2019/05/14 12:47:04 [error] 4395#4395: *180 FastCGI sent in stderr: "PHP message: testlog" while reading response header from upstream, client: 80.151.43.80, server: whatever.com, request: "GET /wp-admin/admin.php?page=payone-settings-account HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "whatever.com"
2019/05/14 12:47:05 [error] 4395#4395: *180 FastCGI sent in stderr: "PHP message: testlog" while reading response header from upstream, client: 80.151.43.80, server: whatever.com, request: "GET /wp-admin/admin.php?page=payone-api-log HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "whatever.com"
2019/05/14 12:47:09 [error] 4395#4395: *257 FastCGI sent in stderr: "PHP message: testlog" while reading response header from upstream, client: 66.249.64.52, server: whatever.com, request: "GET /Widerrufsrecht HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "whatever.com"
```

**Comment by hreinberger** [comment] 2019-06-03 14:47
Hi @vardumper 
yep it seems like we fixed that in our master. Adding a composer.json seems reasonable, so I'll look into that and close this one here.

**Closed by hreinberger** 2019-06-03 14:47 UTC
